import { Resend } from "resend";

const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;
const fromEmail = process.env.RESEND_FROM_EMAIL || "audits@credex.example";

export interface SendAuditReportParams {
  to: string;
  auditId: string;
  savingsUsd: number;
  findingsCount: number;
  auditUrl: string;
}

/**
 * Send audit report email via Resend.
 * Fails silently if Resend is not configured or sending fails.
 */
export async function sendAuditReportEmail(params: SendAuditReportParams): Promise<boolean> {
  const { to, savingsUsd, findingsCount, auditUrl } = params;

  // No API key? Silently skip - email is optional.
  if (!resend) {
    console.log("Resend not configured, skipping email");
    return false;
  }

  try {
    const { error } = await resend.emails.send({
      from: `Credex <${fromEmail}>`,
      to,
      subject: `Your AI Spend Audit - Save $${savingsUsd.toFixed(0)}/mo`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
          <h1 style="color: #1f2937;">Your AI Spend Audit Report</h1>

          <p style="color: #4b5563; line-height: 1.6;">
            We found <strong>${findingsCount} optimization opportunit${findingsCount === 1 ? "y" : "ies"}</strong> in your AI tool stack.
          </p>

          <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 16px; margin: 20px 0;">
            <p style="color: #166534; margin: 0; font-size: 18px; font-weight: 600;">
              Potential Monthly Savings: $${savingsUsd.toFixed(0)}
            </p>
          </div>

          <p style="color: #4b5563; line-height: 1.6;">
            View your full report with detailed recommendations:
          </p>

          <a href="${auditUrl}" style="display: inline-block; background: #2563eb; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: 600; margin: 16px 0;">
            View Full Report
          </a>

          <p style="color: #6b7280; font-size: 14px; margin-top: 32px;">
            This report was generated by <a href="${auditUrl.split("/audit/")[0]}" style="color: #2563eb;">Credex</a>.
          </p>
        </div>
      `,
    });

    if (error) {
      console.error("Resend error:", error);
      return false;
    }

    return true;
  } catch (error) {
    console.error("Email send error:", error);
    return false;
  }
}
